import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="w-full flex gap-8 px-8 py-4 bg-gray-200 mb-4">
          <Link href="/" className="font-bold text-blue-700 hover:underline">Terminal</Link>
          <Link href="/disks" className="font-bold text-blue-700 hover:underline">Visualizador de Discos</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
